import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
import UserButton from "@/components/userbutton/UserButton";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vite & Gourmand",
  description: "Generated by Julie et José",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col font-family-Inter">
        <header>
          <div className="HeaderMain">
            <h1>Vite & Gourmand</h1>
            <div className="HeaderButtons">
              <Link href="/">
                <h1 className="HeaderButton">Acceuil </h1>
              </Link>
              <Link href="/menu">
                <h1 className="HeaderButton">Menu </h1>
              </Link>
              <Link href="/contact">
                <h1 className="HeaderButton">Contact</h1>
              </Link>
              <UserButton />
            </div>
          </div>
        </header>
        <main className="flex-1">
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3000,
            }}
          />
        </main>
        <footer className="FooterMain">
          <div className="FooterContact">
            <h1>Nous Contactez</h1>
            <h3>Tel: **.**.**.**.**</h3>
            <h3>Email: Vite&Gourmand@gmail.com</h3>
            <Link href="/contact">
              <h3 className="FooterButton">Contact</h3>
            </Link>
          </div>
          <div className="FooterNavigation">
            <h1>Navigation</h1>
            <Link href="/avis">
              <h3 className="FooterButton">Avis</h3>
            </Link>
            <Link href="/menu">
              <h3 className="FooterButton">Menu</h3>
            </Link>
            <Link href="/conditions-generales">
              <h3 className="FooterButton">Conditions générale</h3>
            </Link>
            <Link href="/mentions-legales">
              <h3 className="FooterButton">Mentions Légales</h3>
            </Link>
          </div>
          <div className="FooterHours">
            <h1>Horaires</h1>
            <h3>Lundi au Vendredi 12h/14h</h3>
            <h3>Samedi au Dimanche 18h/22h</h3>
          </div>
        </footer>
      </body>
    </html>
  );
}
