import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
import { prisma } from "@/lib/prisma";
import Header from "@/components/header/header";
import LoadingOverlay from "@/components/loading-overlay/LoadingOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vite & Gourmand",
  description: "Generated by Julie et José",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const horaires = await prisma.horaire.findMany({
    orderBy: {
      horaire_id: "asc",
    },
  });
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col font-family-Inter">
        <Header />

        <main className="flex-1">
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3000,
            }}
          />
        </main>
        <footer className="FooterMain">
          <div className="FooterContact">
            <h1>Nous Contactez</h1>
            <h3>Tel: **.**.**.**.**</h3>
            <h3>Email: Vite&Gourmand@gmail.com</h3>
            <Link href="/contact">
              <h3 className="FooterButton">Contact</h3>
            </Link>
          </div>
          <div className="FooterNavigation">
            <h1>Navigation</h1>
            <Link href="/avis">
              <h3 className="FooterButton">Avis</h3>
            </Link>
            <Link href="/menu">
              <h3 className="FooterButton">Menu</h3>
            </Link>
            <Link href="/conditions-generales">
              <h3 className="FooterButton">Conditions générale</h3>
            </Link>
            <Link href="/mentions-legales">
              <h3 className="FooterButton">Mentions Légales</h3>
            </Link>
          </div>
          <div className="FooterHours">
            <h1>Horaires</h1>

            <div className="FooterHoursGrid">
              {horaires.map((horaire) => (
                <div key={horaire.horaire_id} className="FooterHourLine">
                  <span>{horaire.jour}</span>

                  <h3>
                    {horaire.heure_ouverture} - {horaire.heure_fermeture}
                  </h3>
                </div>
              ))}
            </div>
          </div>
        </footer>
        <LoadingOverlay />
      </body>
    </html>
  );
}
